Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Layout/LineLength:
  Max: 400
Metrics/AbcSize:
  Max: 30
Style/MutableConstant:
  Enabled: false